# Generated by Buildr 1.4.0, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "com.log4p"
COPYRIGHT = ""

require 'buildr/scala'

Buildr.settings.build['scala.test'] = "1.0-for-scala-2.8.0.20091026-SNAPSHOT"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << 'http://www.ibiblio.org/maven2'
repositories.remote << 'http://scala-tools.org/repo-snapshots'

desc "Sample SQL implementation in Scala"
define "sql_dsl" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Peter Maas"] = COPYRIGHT
end
